-- =============================================================================
-- E-commerce Funnel & Retention Analysis
-- Step 1: DDL & DB Preparation (PostgreSQL 15+)
-- =============================================================================
-- Author: Lead Data Engineer / Senior Product Analyst
-- Description: Table schema with RANGE partitioning, composite indexes, 
--              and robust 30-minute sessionization logic via window functions.
-- =============================================================================

--------------------------------------------------------------------------------
-- 1. DDL: Create Partitioned Raw Events Table
--------------------------------------------------------------------------------

DROP TABLE IF EXISTS raw_events CASCADE;

CREATE TABLE raw_events (
    event_time    TIMESTAMPTZ NOT NULL,
    event_type    VARCHAR(30) NOT NULL, -- 'view', 'cart', 'remove_from_cart', 'purchase'
    product_id    BIGINT NOT NULL,
    category_id   BIGINT,
    category_code VARCHAR(255),
    brand         VARCHAR(255),
    price         NUMERIC(10, 2) CHECK (price >= 0),
    user_id       BIGINT NOT NULL,
    user_session  UUID
) PARTITION BY RANGE (event_time);

-- Comments on table columns
COMMENT ON TABLE raw_events IS 'Partitioned clickstream event store for e-commerce user behavior';
COMMENT ON COLUMN raw_events.event_time IS 'Timestamp of the event (with timezone)';
COMMENT ON COLUMN raw_events.event_type IS 'Action type: view, cart, remove_from_cart, purchase';
COMMENT ON COLUMN raw_events.user_id IS 'Unique user identification number';
COMMENT ON COLUMN raw_events.user_session IS 'Raw clickstream session UUID generated by frontend';

--------------------------------------------------------------------------------
-- 2. Range Partitioning (Monthly Example partitions for Kaggle Data)
--------------------------------------------------------------------------------

CREATE TABLE raw_events_2019_10 PARTITION OF raw_events
    FOR VALUES FROM ('2019-10-01 00:00:00+00') TO ('2019-11-01 00:00:00+00');

CREATE TABLE raw_events_2019_11 PARTITION OF raw_events
    FOR VALUES FROM ('2019-11-01 00:00:00+00') TO ('2019-12-01 00:00:00+00');

CREATE TABLE raw_events_2019_12 PARTITION OF raw_events
    FOR VALUES FROM ('2019-12-01 00:00:00+00') TO ('2020-01-01 00:00:00+00');

CREATE TABLE raw_events_default PARTITION OF raw_events DEFAULT;

--------------------------------------------------------------------------------
-- 3. Optimization Indexes
--------------------------------------------------------------------------------
-- Primary indexing strategy:
-- 1. (user_id, event_time): Crucial for sessionization, window functions & user-level histories.
-- 2. (user_session): Fast lookup by session ID when raw session UUID is present.
-- 3. (event_type, event_time): Speeds up funnel aggregation and filtering by event type.

CREATE INDEX idx_raw_events_user_time 
    ON raw_events (user_id, event_time ASC);

CREATE INDEX idx_raw_events_session 
    ON raw_events (user_session) 
    WHERE user_session IS NOT NULL;

CREATE INDEX idx_raw_events_type_time 
    ON raw_events (event_type, event_time);

CREATE INDEX idx_raw_events_category_brand 
    ON raw_events (category_code, brand) 
    WHERE category_code IS NOT NULL;


--------------------------------------------------------------------------------
-- 4. Sessionization Logic (30-Minute Inactivity Window via LAG)
--------------------------------------------------------------------------------
-- Business Context: Frontend session IDs (user_session) can be missing or invalid 
-- due to cookie expiration, multi-device switches, or SDK errors.
-- We synthesize a robust `calculated_session_id` using a 30-minute inactivity threshold.

CREATE OR REPLACE VIEW v_events_sessionized AS
WITH event_lags AS (
    SELECT
        event_time,
        event_type,
        product_id,
        category_id,
        category_code,
        brand,
        price,
        user_id,
        user_session AS raw_user_session,
        -- Fetch previous event time per user
        LAG(event_time) OVER (
            PARTITION BY user_id 
            ORDER BY event_time ASC
        ) AS prev_event_time
    FROM raw_events
),
session_flags AS (
    SELECT
        *,
        -- Mark start of new session if gap > 30 minutes (1800 seconds) or first event
        CASE 
            WHEN prev_event_time IS NULL THEN 1
            WHEN EXTRACT(EPOCH FROM (event_time - prev_event_time)) > 1800 THEN 1
            ELSE 0
        END AS is_new_session
    FROM event_lags
),
session_numbering AS (
    SELECT
        *,
        -- Running cumulative sum of session flags per user generates sequential session number
        SUM(is_new_session) OVER (
            PARTITION BY user_id 
            ORDER BY event_time ASC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS user_session_seq
    FROM session_flags
)
SELECT
    event_time,
    event_type,
    product_id,
    category_id,
    category_code,
    brand,
    price,
    user_id,
    raw_user_session,
    -- Construct unique calculated session identifier: {user_id}_s{user_session_seq}
    user_id::text || '_s' || user_session_seq::text AS calculated_session_id,
    COALESCE(
        user_session::text, 
        user_id::text || '_s' || user_session_seq::text
    ) AS effective_session_id
FROM session_numbering;

COMMENT ON VIEW v_events_sessionized IS 'View with synthesized 30-min inactivity sessions (calculated_session_id)';
